#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6
sudo apt-get -y update
sudo apt-get -y install haproxy=2.6.\*
sudo chown -R $USER:$USER /etc/haproxy/haproxy.cfg
sudo printf %s "
listen www
    bind :80
    mode http
    balance roundrobin
    server 21966-web-01 3.238.87.75:80 check
    server 21966-web-02 3.234.245.243:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart