#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using while

num=0
while [ $num -lt 9 ]
do
    echo "Best School"
    num=$((num+1))
    if [ $num -eq 8 ]
    then
        echo "Hi"
    continue
    fi
done