#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using while

num=0
while [ $num -lt 10 ]
do
    if [ $num -eq 4 ]
    then
        echo "bad luck"
    elif [ $num -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    num=$((num+1))
done